backend_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls'))
]

review/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.album_list),
    path('accounts/profile/', views.profile, name='profile'),
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name="register"),
    path("logout_user", views.logout_user, name="logout"),
    path('albums/', views.album_list, name='albums'),
    path('search/', views.genre_list, name='song_search'),
    path('albums/<int:pk>/', views.album_detail),
    path('genre/<str:genre_name>/', views.albums_in_genre),
    path('song/<int:pk>/', views.songs_detail, name='song_detail'),
    path('songedit/<int:song_pk>/', views.song_edit, name='song_edit'),
    path('my_playlist/', views.my_playlist, name='my_playlist'),
    path('add_song_to_playlist/<int:pk>', views.add_song_to_playlist, name='add_song_to_playlist'),
    path('playlist/<int:pk>', views.playlist_detail, name='playlist_detail'),
    path('create_playlist/', views.create_playlist, name='create_playlist'),
    path('/delete/<int:playlist_pk>/<int:song_pk>', views.delete_song_from_playlist, name='delete_song_from_playlist'),
    path('/delete_playlist/<int:pk>', views.delete_playlist, name='delete_playlist')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

review/models.py
from django.contrib.auth.models import User
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=255)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class Album(models.Model):
    name = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    release_date = models.DateField(null=True)
    genre = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Song(models.Model):
    name = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    length = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover = models.ImageField(null=True, blank=True, upload_to="song_covers/")

    def __str__(self):
        return self.name
class Playlist(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class PlaylistSong(models.Model):
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

review/forms.py
from django.contrib.auth.forms import UserCreationForm

from django import forms

from .models import Song, User, Playlist


class SearchForm(forms.Form):
    search = forms.CharField(required=False, min_length=2)
    search_in = forms.ChoiceField(required=False,
                                  choices=(
                                      ("Song", "Song"),
                                      ("Artist", "Artist")),
                                  widget=forms.Select(attrs={
                                      'class': 'my-select-class',
                                      'style': 'width: 250px; height: 30px; border: 1px solid #ccc; border-radius: '
                                               '4px; padding: 5px; font-size: 16px; box-shadow: 0 0 5px rgba(0, 0, 0,'
                                               ' 0.3);'
                                  }))


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['name', 'artist', 'album', 'length', 'cover']
        labels = {
            'name': 'Song Name',
            'length': 'Length (in seconds)',
            'artist': 'Artist Name',
            'album': 'Album Name'
        }

class PlayListForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['user', 'name', 'description']



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'email-input',
        'style': 'width: 250px; height: 30px; border: 1px solid black; border-radius: 4px;'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'my-class',
                                                             'style': 'width: 250px; height: 30px; border: 1px solid black; border-radius: 4px;'}))

    password1 = forms.CharField(label="Password", required=True, widget=forms.PasswordInput(attrs={
        'style': 'width: 250px; height: 30px; border: 1px solid black; border-radius: 4px;'}))

    password2 = forms.CharField(label="Password Confirmation", required=True,
                                    widget=forms.PasswordInput(attrs={
                                        'style': 'width: 250px; height: 30px; border: 1px solid black; border-radius: '
                                                 '4px;'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

review/views.py
from django.contrib.auth.decorators import login_required

from .forms import *
from .models import (Artist, Album, Song, Playlist, PlaylistSong)
from django.contrib import messages
from django.contrib.auth.models import auth
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.http import FileResponse
from django.views import View
import os


def album_list(request):
    albums = Album.objects.all()
    albums_with_genre = {}

    for album in albums:
        if album.genre not in albums_with_genre:
            albums_with_genre[album.genre] = []
        albums_with_genre[album.genre].append(album)

    return render(request, "album_list.html", {'albums_with_genre': albums_with_genre})


def album_detail(request, pk):
    album = Album.objects.get(pk=pk)
    songs = Song.objects.filter(album__name=album.name)

    return render(request, "album_songs.html", {'songs': songs, 'album': album})


def playlist_detail(request, pk):
    playlist = Playlist.objects.get(pk=pk)
    songs = PlaylistSong.objects.filter(playlist=playlist)

    return render(request, "playlist_songs.html", {'playlist': playlist, 'songs': songs})

def delete_song_from_playlist(request, playlist_pk, song_pk):
    song = PlaylistSong.objects.filter(playlist_id=playlist_pk, song_id=song_pk)
    song.delete()

    playlist = Playlist.objects.get(pk=playlist_pk)
    songs = PlaylistSong.objects.filter(playlist=playlist)

    return render(request, "playlist_songs.html", {'playlist': playlist, 'songs': songs})


def genre_list(request):
    search_text = request.GET.get("search", "")
    form = SearchForm(request.GET)
    songs = set()

    if form.is_valid() and form.cleaned_data["search"]:
        search = form.cleaned_data["search"]
        search_in = form.cleaned_data.get("search_in") or "Song"
        if search_in == "Song":
            songs = Song.objects.filter(name__icontains=search)
        else:
            artist_names = Artist.objects.filter(name__icontains=search)

            for artist in artist_names:
                for song in artist.song_set.all():
                    songs.add(song)

    albums = Album.objects.all()
    genre_set = set()

    for album in albums:
        if len(genre_set) == 4:
            break
        genre_set.add(album.genre)

    return render(request, "search.html",
                  {'form': form, "search_text": search_text, "songs": songs, 'genre_set': genre_set})


def albums_in_genre(request, genre_name):
    albums = Album.objects.all()
    albums_of_one_genre = []

    for album in albums:
        if genre_name == album.genre:
            albums_of_one_genre.append(album)

    return render(request, "albums_of_one_genre.html",
                  {'genre': genre_name, 'albums_of_one_genre': albums_of_one_genre})


def songs_detail(request, pk):
    song = Song.objects.get(pk=pk)

    return render(request, "song_detail.html", {'song': song})


def search_song(request, name):
    name = request.GET.get('search')
    songs = Song.objects.all()
    list_of_songs = []

    for song in songs:
        if song.name == name:
            list_of_songs.append(song)

    return render(request, "song_detail.html", {'list_of_songs': list_of_songs})


def song_edit(request, song_pk):
    song = get_object_or_404(Song, pk=song_pk)

    if request.method == 'POST':
        form = SongForm(request.POST, request.FILES, instance=song)
        if form.is_valid():
            song_instance = form.save(commit=False)
            if 'cover' in request.FILES:
                song_instance.cover = request.FILES['cover']
            song_instance.save()
            return redirect('song_detail', song_pk)
    else:
        form = SongForm(instance=song)

    return render(request, 'song_edit.html', {'form': form})


@login_required
def my_playlist(request):
    user_playlists = Playlist.objects.filter(user=request.user)

    return render(request, 'my_library.html', {'playlists': user_playlists})

def delete_playlist(request, pk):
    playlist = Playlist.objects.get(pk=pk, user=request.user)
    playlist.delete()

    user_playlists = Playlist.objects.filter(user=request.user)
    return render(request, 'my_library.html', {'playlists': user_playlists})



def add_song_to_playlist(request, pk):
    song = Song.objects.get(pk=pk)
    playlists = Playlist.objects.filter(user=request.user)

    if request.method == 'POST':
        playlist_id = request.POST.get('playlist')
        playlist = Playlist.objects.get(pk=playlist_id)
        if not PlaylistSong.objects.filter(playlist=playlist, song=song).exists():
            PlaylistSong.objects.create(playlist=playlist, song=song)
        return redirect('playlist_detail', pk=playlist_id)

    return render(request, 'add_song_to_playlist.html', {'playlists': playlists, 'song': song})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('albums')
    else:
        form = RegistrationForm()

    context = {'form': form}
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('albums')
        else:
            messages.error(request, 'Invalid Username or Password')
            return redirect('login')
    else:
        return render(request, 'login.html')


def logout_user(request):
    auth.logout(request)
    return redirect('albums')


@login_required
def profile(request):
    user = request.user
    permissions = user.get_all_permissions()
    return render(request, 'profile.html', {'user': user, 'permissions': permissions})


def create_playlist(request):
    if request.method == 'POST':
        form = PlayListForm(request.POST)
        form.user = request.POST.get('user')
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/my_playlist')
    else:
        form = PlayListForm()
    return render(request, 'create_playlist.html', {'form': form})

review/templates/add_song_to_playlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3 class="mb-4 text-white">Select the playlist you want to add music - {{ song.name }}</h3>
            </div>
        </div>

        <div class="row">
            {% for playlist in playlists %}

                <div class="col-md-3 " >
                    <div class="card">
                        <img src="
                                {% if playlist.songs.count > 0 %}{{ playlist.songs.first.cover.url }}{% else %}{% static 'Spotify-App-Icon-Large.png' %}{% endif %}"
                             class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ playlist.name }}</h5>
                            <p class="card-text">{{ playlist.description }}</p>
                            <form method="POST" action="{% url 'add_song_to_playlist' pk=song.pk %}">
                                {% csrf_token %}
                                <input style="display:none;" type="number" name="playlist" value="{{ playlist.pk }}"
                                       required>
                                <button class="add-to-playlist-button" type="submit">Add</button>
                            </form>

                        </div>
                    </div>
                </div>
            {% empty %}
                 <h4 class="ml-2 text-white">You don't have any playlists yet</h4>
            {% endfor %}
        </div>
    </div>
{% endblock %}

review/templates/album_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Welcome to our music platform!</h1>

        <div class="albums">
            {% for genre, albums in albums_with_genre.items %}
                <h2 >{{ genre }}</h2>
                <ul class="genre">
                    {% for album in albums %}
                        <a class="album" style="background-color:#a5a5a5;" href="/albums/{{ album.id }}/">{{ album.name }}<img src="{% static 'Spotify-App-Icon-Large.png' %}" alt=""></a>
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

review/templates/album_songs.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <h1>Album - {{ album.name }}</h1>

    {% if songs %}

        <ul class="songs">
            {% for song in songs %}
                <a style="text-decoration: none" href="/song/{{ song.id }}/">
                    <li class="song">
                        {{ song.name }}
                    </li>
                </a>
            {% endfor %}
        </ul>
    {% else %}
            <h2>Album is empty</h2>
    {% endif %}

    </div>
{% endblock %}

review/templates/albums_of_one_genre.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <h1>{{ genre }}</h1>

        <div class="albums">
                <ul class="genre">
                    {% for album in albums_of_one_genre %}
                        <a style="background-color: #a5a5a5" class="album" href="/albums/{{ album.id }}/">{{ album.name }}<img src="{% static 'Spotify-App-Icon-Large.png' %}" alt=""></a>
                    {% endfor %}
                </ul>
        </div>
    </div>
{% endblock %}

review/templates/create_playlist.html
{% extends 'base.html' %}
{% block content %}

    <div class="container mx-auto px-4 py-8">

        <h1 class="text-3xl font-bold text-white mb-8">Create new playlist</h1>

        <form method="POST" action="{% url 'create_playlist' %}">
            {% csrf_token %}
            <input type="hidden" name="user" value="{{ request.user.id }}">

            <div class="mb-4">
                <label for="playlist_name" class="block text-white font-bold mb-2">Playlist name:</label>
                <input type="text" id="playlist_name" name="name"
                       class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                       required>
            </div>

            <div class="mb-4">
                <label for="playlist_description" class="block text-white font-bold mb-2">Playlist description:</label>
                <textarea id="playlist_description" name="description"
                          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"></textarea>
            </div>


            <div class="flex justify-end">
                <button type="submit"
                        class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Create
                </button>
            </div>
        </form>
    </div>

{% endblock %}

review/templates/my_library.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h3 class="mb-4 text-white">My playlist</h3>
            </div>
        </div>

        <div class="" style="display: flex;">
            {% for playlist in playlists %}
                <div class="" style="display: flex; flex-direction: column">
                <a class="album" style="background-color:#a5a5a5;"
                   href="{% url 'playlist_detail' playlist.pk %}">{{ playlist.name }}<img
                        src="{% static 'Spotify-App-Icon-Large.png' %}" alt=""></a>

                <form action="{% url 'delete_playlist' playlist.pk %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="play-button" style="width: 150px; margin-left: 17px; font-size: 20px; margin-top: 20px; background-color: #c94747">Delete</button>
                </form>
</div>
            {% empty %}
                <h4 class="ml-2 text-white">You don't have any playlist yet</h4>
            {% endfor %}
        </div>
    </div>
{% endblock %}

review/templates/playlist_songs.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Playlist - {{ playlist.name }}</h1>

        {% if songs %}

            <ul class="songs">
                {% for song in songs %}
                    <a style="text-decoration: none;color: white" href="/song/{{ song.song.pk }}/">
                        <li class="song">
                            <div style="display: flex; flex-direction: row; justify-content: space-between">
                                <div>{{ song.song }}</div>

                                <div>
                                    <form action="{% url 'delete_song_from_playlist' playlist.pk song.song.pk %}"
                                          method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="delete-button" style="color: #10B981">Delete
                                        </button>
                                    </form>
                                </div>

                            </div>
                        </li>

                    </a>
                {% endfor %}
            </ul>

        {% else %}
            <h3 class="text-white">You haven't added anything to your playlist yet</h3>
        {% endif %}
    </div>
{% endblock %}

review/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css">
</head>
<body class="bg-gray-900">
<div class="flex h-screen">
    <div class="m-auto">
        <div class="w-full max-w-xs">
            <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
                {% csrf_token %}

                <h1 class="text-center font-bold text-gray-800 text-2xl mb-6">Register</h1>
                <div class="mb-4">
                    {{ form.username.label }}
                    <br>
                    {{ form.username }}
                </div>
                <div class="mb-4">
                    {{ form.email.label }}
                    <br>
                    {{ form.email }}
                </div>
                <div class="mb-6">
                    {{ form.password1.label }}
                    <br>
                    {{ form.password1 }}
                </div>
                <div class="mb-6">
                    {{ form.password2.label }}
                    <br>
                    {{ form.password2 }}

                </div>
                <div class="error" style="color: red">
                    {{ form.errors }}
                </div>

                <div class="flex items-center justify-between">
                    <input class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                           type="Submit" value="Register Now">
                    <a class="inline-block align-baseline font-bold text-sm text-gray-500 hover:text-gray-800" href="{% url 'login' %}">
                        Have an account?
                    </a>
                </div>
            </form>
            <p class="text-center text-gray-500 text-xs">
                &copy;2023 Spotify, Inc. All rights reserved.
            </p>
        </div>
    </div>
</div>
</body>
</html>

review/templates/search.html
{% extends 'base.html' %}

{% block content %}

    <header class="bg-gray-900">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-white">
                Music for everyone.
            </h1>
            <p class="mt-4 max-w-2xl text-gray-500">
                Millions of songs. No credit card needed.
            </p>
            <div class="mt-8">
                <form>

                    <div style="display: flex; flex-direction: column; margin-bottom: 10px">
                    <div class="flex flex-col sm:flex-row justify-center max-w-md mx-auto py-2 px-3 sm:px-6 lg:px-8">
                        <input type="text" name="search" id="search" placeholder="Search"
                           class="flex-1 appearance-none border-2 border-gray-300 rounded-md w-full py-1 sm:px-7 text-gray-700 leading-tight focus:outline-none focus:border-green-500 focus:ring-green-500">
                        <button type="submit"
                                class="mt-2 sm:mt-0 sm:ml-3 inline-flex items-center px-6 py-2
                                border border-transparent text-base font-medium rounded-md shadow-sm
                                text-white bg-green-500 hover:bg-green-600 focus:outline-none focus:ring-2
                                focus:ring-offset-2 focus:ring-green-500">
                                Enter
                        </button>
                    </div>
                        <div style="display: flex; justify-content: center; margin-right: 100px">  {{ form.search_in }} </div>
                    </div>
                </form>

                {% if form.is_valid and search_text %}
                    <h3 style="color: white">Search Results for <em>{{ search_text }}</em></h3>
                    <ul>

                    {% for song in songs %}
                        <li class="list-group-item">
                            <span class="text-info">Title: </span> <a
                                style="text-decoration: none;" href="{% url 'song_detail' song.pk %}">{{ song }}</a>
                            <br/>
                            <span class="text-info">Artist: </span> {{ song.artist }}
                        </li>
                        {% empty %}
                            <li class="list-group-item">No results found.</li>
                        {% endfor %}
                    </ul>

                {% endif %}

            </div>
        </div>
    </header>

    <main>
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <div class="px-4 py-6 sm:px-0">

                <h2 class="text-lg font-medium font-bold text-white">Recommended for you</h2>
                <div class="grid grid-cols-1 gap-6 mt-6 sm:grid-cols-2 lg:grid-cols-3">

                    {% for genre in genre_set %}

                    <div class="group relative">

                        <div class="relative w-full h-80 rounded-lg overflow-hidden">
                            <img src="https://source.unsplash.com/random/800x800?music" alt="Music"
                                class="w-full h-full object-center object-cover">

                            <div class="absolute inset-0 bg-gradient-to-b from-transparent to-black opacity-50 group-hover:opacity-75"></div>
                            <button class="absolute inset-0 w-full h-full flex items-center justify-center opacity-0 group-hover:opacity-100 focus:outline-none" onclick="window.location.href='/genre/{{ genre }}/'">
                                <h1 class="text-lg font-medium font-bold text-white">{{ genre }}</h1>

                                <svg class="h-20 w-20 text-white fill-current" viewBox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7 4v12l9-6-9-6z"/>
                                </svg>
                            </button>
                        </div>

                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </main>

{% endblock %}

review/templates/song_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="song-detail">

        {% if song.cover %}
            <img class="album-cover" src="{{ song.cover.url }}" alt="{{ song.album }}">
        {% else %}
            <img class="album-cover" src="{% static 'Spotify-App-Icon-Large.png' %}" alt="{{ song.album }}">
        {% endif %}

        <div class="song-info">
            <h1 class="song-title">{{ song.name }}</h1>
            <h2 class="artist-name">{{ song.artist }}</h2>


            <div class="song-meta">
                <p class="album-name">{{ song.album }}</p>
                <p class="release-date">{{ song.created_at }}</p>
                <p class="duration">{{ song.length }}</p>
            </div>

            <div class="song-actions">
                <button class="play-button">Play</button>
                {% if user.is_authenticated %}
                    <a href="{% url 'add_song_to_playlist' song.pk %}"><button class="add-to-playlist-button">Add to Playlist</button></a>

                    {% if user.is_staff or user.is_superuser %}
                        <a href="{% url 'song_edit' song.pk %}">
                            <button class="add-to-playlist-button">Edit song</button>
                        </a>
                    {% endif %}
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

review/templates/song_edit.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Edit Song{% endblock %}

{% block content %}

    <div class="container mx-auto py-8">
        <h1 class="text-3xl font-bold mb-8">Edit Song</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-white font-bold mb-2" for="id_name">Name:</label>
                <input type="text" name="name" id="id_name" value="{{ form.name.value }}" class="form-input">
                {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        <p class="text-red-500 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-4">
                <label class="block text-white font-bold mb-2" for="id_artist">Artist:</label>
                {{ form.artist|as_crispy_field }}
                {% if form.artist.errors %}
                    {% for error in form.artist.errors %}
                        <p class="text-red-500 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-4">
                <label class="block text-white font-bold mb-2" for="id_album">Album:</label>
                {{ form.album|as_crispy_field }}
                {% if form.album.errors %}
                    {% for error in form.album.errors %}
                        <p class="text-red-500 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-4">
                <label class="block text-white font-bold mb-2" for="id_length">Length:</label>
                <input type="text" name="length" id="id_length" value="{{ form.length.value }}" class="form-input">
                {% if form.length.errors %}
                    {% for error in form.length.errors %}
                        <p class="text-red-500 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-4">
                <label class="block text-white font-bold mb-2" for="id_cover">Cover:</label>
                {% if form.cover.value %}
                    <img src="{{ form.cover.value.url }}" alt="{{ form.cover.value.name }}"
                         class="w-64 h-64 object-cover">
                {% endif %}
                <input type="file" name="cover" id="id_cover" class="form-input">
                {% if form.cover.errors %}
                    {% for error in form.cover.errors %}
                        <p class="text-red-500 text-sm italic mt-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
                <button type="submit"
                        class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mt-4">Save
                </button>
        </form>
    </div>
{% endblock %}